# Generated by Django 4.2.26 on 2025-11-26 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('invited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('ums_count', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latest_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('latest_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=32)),
                ('occupation', models.CharField(max_length=255)),
                ('timings', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('do_you_exercise', models.CharField(max_length=64)),
                ('hours_sleep', models.CharField(max_length=64)),
                ('liters_water', models.CharField(max_length=64)),
                ('loss_of_energy', models.CharField(max_length=32)),
                ('veg_nonveg', models.CharField(blank=True, max_length=32, null=True)),
                ('personal_health_history', models.JSONField(blank=True, null=True)),
                ('transformation_targets', models.CharField(max_length=255)),
                ('tried_diet_programs', models.BooleanField(default=False)),
                ('surveyed_by', models.CharField(max_length=255)),
                ('available_time', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.member')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category_data', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='core.member')),
            ],
            options={
                'ordering': ['-checkup_date'],
            },
        ),
        migrations.CreateModel(
            name='BodyComponentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('visceral_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trunk_subcutaneous_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_men', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_women', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_age', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmr_rm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('skeletal_muscle_men', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skeletal_muscle_women', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fluids', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_evaluations', to='core.member')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.member')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'member__full_name'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
