# Generated by Django 4.2.26 on 2025-12-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(default='Other', max_length=16),
        ),
        migrations.AddField(
            model_name='registration',
            name='invited_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
