# Generated by Django 4.2.26 on 2025-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registration_gender_registration_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.CharField(blank=True, choices=[('TRIAL', 'Trial'), ('UMS', 'UMS'), ('COMPLEMENT', 'Complement')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_total_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='membership',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('UMS', 'UMS'), ('COMPLEMENT', 'Complement')], default='UMS', max_length=16),
        ),
    ]
