# Generated by Django 4.2.26 on 2025-12-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_membership_member_membership_total_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='timings',
        ),
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='initial_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='plan_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
