# Generated by Django 4.2.26 on 2025-12-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_registration_timings_registration_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodycomponentevaluation',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodycomponentevaluation',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bodycomponentevaluation',
            name='fluids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
