# Generated by Django 4.2.26 on 2025-12-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bodycomponentevaluation_analysis_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership',
            field=models.CharField(blank=True, choices=[('TRIAL', 'Trial'), ('UMS', 'UMS'), ('COMPLEMENT', 'Complement'), ('OTHERS', 'Others')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='membership',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('UMS', 'UMS'), ('COMPLEMENT', 'Complement'), ('OTHERS', 'Others')], default='UMS', max_length=16),
        ),
    ]
